services:
  - type: web
    name: openrequest.co
    runtime: static
    buildCommand: 'true'
    staticPublishPath: ./
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains"
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Content-Security-Policy
        value: >-
          default-src 'self';
          style-src 'self';
          font-src 'self';
          img-src 'self' data: https://openrequest.openstatus.dev;
          script-src 'self' https://app.cal.com https://app.kobbe.io;
          frame-src https://app.cal.com https://cal.com;
          connect-src 'self' https://app.cal.com https://app.kobbe.io;
          frame-ancestors 'none';
          base-uri 'self';
          upgrade-insecure-requests
